Feat/#7
woorifisa-service-dev-3rd/backend-1st-casino pull request #11
Opened 2024-08-21 11:59 UTC by gusdk19

## 🎈 이슈 번호
#7

## ✅ 작업 사항
- bank 구현
- 게임왕, 게임거지 구현

## 📢 기타 사항

2024-08-21 20:41 UTC, cbj0010 requested changes
리뷰 함 봐주세용~ 고생했서용

2024-08-21 20:41 UTC, cbj0010 commented on casino/src/data/RecordDAO.java
> +    }
Connection을 생성자로 받아오는 이유가 뭔가요?🤔

2024-08-21 20:41 UTC, cbj0010 commented on casino/src/data/RecordDAO.java
> +        try (PreparedStatement updateLosesStatement = connection.prepareStatement(showLosesQuery);
PreparedStatement도 따로 뺴고 써보는건 어떨까요?😃

2024-08-21 20:41 UTC, cbj0010 commented on casino/src/data/BankDAO.java
> +    }
Connection을 생성자로 받아오는 이유가 뭔가요?🤔

2024-08-22 00:15 UTC, gusdk19 commented on casino/src/data/RecordDAO.java
> +    }
DAO 파일마다 따로 connection을 또 선언하고 사용할 필요 없이 main 코드로부터 connection을 넘겨 받아서 사용하기 위해 사용했습니다!
이렇게 해주면 Record 클래스의 showKing 메서드에서  RecordDAO recordDAO = new RecordDAO(connection); 이렇게 작성했을 때
RecordDAO에서는 connection 객체를 직접 생성하지 않고 showKing에서 넘겨준 connection을 사용할 수 있는 것이죠 ☺️

2024-08-22 00:26 UTC, gusdk19 commented on casino/src/data/RecordDAO.java
> +        try (PreparedStatement updateLosesStatement = connection.prepareStatement(showLosesQuery);
PreparedStatement를 따로 빼고 작성할 수도 있습니다!
그런데 PreparedStatement를 블록 밖으로 빼고 작성하려면 자원 해제를 위해 try-catch-finally 구문을 사용하고, finally 블록에서 따로 close() 해주어야 합니다.
그래서 자원을 자동으로 해제해주는 try-with-resources 구문을 사용하여 코드를 간결화하고 혹시나 발생할 수 있는 자원 해제 문제를 보완하고자 했습니다!

2024-08-22 00:28 UTC, gusdk19 commented on casino/src/data/BankDAO.java
> +    }
앞선 답변과 같습니다 😀 이해 안 가시면 또 알려 주세요! 저도 더 공부하고 있겠습니다 ..ㅎㅎ

2024-08-22 05:49 UTC, cbj0010 approved these changes

2024-08-22 05:50 UTC, merged